# Generated by Django 3.2.3 on 2021-05-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='VALEUR_TEMP',
            field=models.CharField(max_length=10),
        ),
    ]
