# Generated by Django 3.2.3 on 2021-06-10 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_alter_temperature_valeur_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='VALEUR_TEMP',
            new_name='temperature',
        ),
        migrations.AddField(
            model_name='temperature',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
