# Generated by Django 3.2.3 on 2021-06-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20210610_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='Timestamp',
            new_name='moment',
        ),

        migrations.AlterModelTable(
                name = 'Temperature',
                table = 'temperature'
        ),


    ]
