# Generated by Django 3.2.3 on 2021-06-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_rename_timestamp_temperature_moment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temperature',
            table=None,
        ),
    ]
